-- 1 평균 일일 대여 요금 구하기 
SELECT round(AVG(DAILY_FEE),0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE = 'SUV';

-- 2 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD,'%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME;

-- 3 과일로 만든 아이스크림 고르기
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR=I.FLAVOR
WHERE F.TOTAL_ORDER > 3000
AND I.INGREDIENT_TYPE = 'fruit_based';

-- 4 3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = '03'
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;

-- 5 서울에 위치한 식당 목록 출력하기
select r.rest_id,i.REST_NAME,i.FOOD_TYPE,i.FAVORITES,i.ADDRESS,round(avg(r.review_score),2) as score
from rest_review r
join rest_info i on r.rest_id = i.rest_id
group by rest_id
having i.ADDRESS like '서울%'
order by score desc, i.FAVORITES desc;

-- 6 조건에 부합하는 중고거래 댓글 조회하기
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d')
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = '2022'
AND MONTH(B.CREATED_DATE) = '10'
ORDER BY R.CREATED_DATE, B.TITLE;

-- 7 인기있는 아이스크림
SELECT flavor
from FIRST_HALF 
order by TOTAL_ORDER desc, SHIPMENT_ID;

-- 8 강원도에 위치한 생산공장 목록 출력하기
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC;

-- 9 12세 이하인 여자 환자 목록 출력하기
SELECT PT_NAME,PT_NO,GEND_CD,AGE,IFNULL(TLNO,'NONE') AS TLNO
FROM PATIENT
WHERE AGE<=12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME;

-- 10 업그레이드 된 아이템 구하기
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
	SELECT T.ITEM_ID
	FROM ITEM_TREE T
	WHERE PARENT_ITEM_ID IN(
	SELECT ITEM_ID
	FROM ITEM_INFO
	WHERE RARITY = 'RARE'
	)
)
ORDER BY ITEM_ID DESC;